Repository trevolia/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#6 Integrar arquitetura v1.0
  docs/arquitetura.md
Labels: arquitetura

#7 Integrar implementação v1.0
  src/jogovelha.py
Labels: programação

#13 Gerar release v1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações

#16 Integrar arquitetura v1.1
  docs/arquitetura.md
Labels: arquitetura

#17 V1.1 teste
  src/testes_inic.py
  src/testes_jogada.py
  src/testes_jogar.py
Labels: testes

#18 Update jogovelha.py
  src/jogovelha.py
Labels: programação

#19 Release v1.1
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogada.py
  src/testes_jogar.py
Labels: operações
